FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG PROJECT_FILE

WORKDIR /src
COPY . .

RUN dotnet restore "$PROJECT_FILE"
RUN dotnet publish "$PROJECT_FILE" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
ARG APP_DLL

ENV APP_DLL=$APP_DLL
ENV ASPNETCORE_URLS=http://+:8080

WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "dotnet \"$APP_DLL\""]